### PR TITLE
Surround the ab_glyph pixmap with a 1px border

### LINKED ISSUE #50: `ab_glyph` renderer panics with a scale factor > 2
I set the scale factor in GNOME to 225%, which results in an integer scale factor of 3. When dragging the example window to the screen with the higher scale factor, the program crashes.

```
thread 'main' panicked at src/title/ab_glyph_renderer.rs:102:40:
index out of bounds: the len is 30051 but the index is 30282
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by Friz64**
ab_glyph apparently likes to draw outside of its area in some cases.

Fixes #50

### CODE REVIEW

File: src/title/ab_glyph_renderer.rs [hunk 1]
```diff
@@ -80,8 +80,8 @@ impl AbGlyphTitleText {
 
         let glyphs = self.layout(&font);
         let last_glyph = glyphs.last()?;
-        let width = (last_glyph.position.x + font.h_advance(last_glyph.id)).ceil() as u32;
-        let height = font.height().ceil() as u32;
```
Comment (PolyMeilex) [inline src/title/ab_glyph_renderer.rs:84]: A week from now, noone will remember why there is + 2 here.
Let's add a short comment along the lines of `+ 2 because ab_glyph likes to draw outside of its area, so we add 1px border around the pixmap`

**Review by PolyMeilex — APPROVED** [review]

File: src/title/ab_glyph_renderer.rs (hunk 1 above)
Comment (Friz64) [reply src/title/ab_glyph_renderer.rs:84]: Good point 😅

**Comment by PolyMeilex** [comment]
Thanks! :rocket:
